server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: afferent-coupling
          uri: lb://AFFERENT-COUPLING-API
          predicates:
            - Path=/api/afferent-coupling/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: API-GATEWAY
    prefer-ip-address: true
